apiVersion: v1
kind: ConfigMap
metadata:
  name: base-credentials-configmap
data:
  # Database
  DB_USER: root
  DB_PASSWORD_ENCRYPTED: CAmYi6FVzWQ3KgGDrZxIgduW4efo8AWWN/vzjNFjOs5qNjov9vNSi8bETtg3+yEZrYyBHn/nf9hsPIzRxgc5ixS0GdTbQWBmmRlZ/RAP8eknaQN2N7LeJSsZUwCrfFsJeJH8XQ8llDGReNU8s0T3rBkM5lk9owiIPRDRhIl4lYB216+W0kahh+ADNbgq+FkMa/dozx1zArtTSwIN+cNZwNTkXc6R66hC3bNzG3PxqqhEIiw6H3L72nf1EroS9HNT37fzszQytb1KIeNgH3kz8pQ1OozIcrYuVA8l9SeGUwYFJ1Ws3KvQI2yTNx/hgfxZiTxB2nVMDLoayjZPSXRsYJf8xJZAi+Es5KnijZDc95G+zDQKqbCVdcOgQ19I1NoTxnW/vBBm1zBZTrCvSUR7Q6DhK2QhKmabSDxKyrWTKmXgSUeMgh9Yj4MBRzbaBaKryt8vtRVMEa8E6M9jcGrJ0Y+GfmXCpc56SPKFvEMSgFvzTjhOhxgafKgShj61f41puUOcOzEoucVP/FxIgk+ODXWtvY/p77vrpB2ADLrBjzWn3h97n3cNirn2BFRzZ1tj88E8syz5lxgOsE7PTCR+vQHnVMjLUQoPZKlSZtTecHr/4hQTei9ax2otfFoQzJPU7Gw/Yx8cn5kYXHHdwskaXbmvfUZ1Zcxby6GsGbbaEYA=

