apiVersion: v1
kind: ConfigMap
metadata:
    name: base-database-configmap
data:
  DB_HOST: dev.db
  DB_NAME: schematic
  DB_TYPE: starrocks
  DB_ADAPTER: mysql2
  DATABASE_URL: mysql2://dev.db:9030/schematic

