apiVersion: v1
kind: ConfigMap
metadata:
  name: base-routine-load-properties
  namespace: schematic
data:
  # Routine Load Properties
  ROUTINE_LOAD_CONCURRENT_NUMBER: 3
  ROUTINE_LOAD_FORMAT: json
  ROUTINE_LOAD_MAX_ERROR_NUMBER: 0
  ROUTINE_LOAD_MAX_FILTER_RATIO: 1.0
  ROUTINE_LOAD_MAX_BATCH_INTERVAL: 10
  ROUTINE_LOAD_MAX_BATCH_ROWS: 2000000
  ROUTINE_LOAD_TASK_CONSUME_SECOND: 15
  ROUTINE_LOAD_TASK_TIMEOUT_SECOND: 60

  # Deployment Configuration
  MIGRATION_MODE: true
  HYDRATE: true
  RESOURCE_DIR: db/starrocks
  WORK_DIR: 
  LOG_LEVEL: 1
  SQL_LOG_LEVEL: debug

