apiVersion: v1
kind: ConfigMap
metadata:
  name: base-routine-load-credentials
  namespace: schematic
data:
  # Kafka credentials
  KAFKA_BROKER_LIST: broker1:9092,broker2:9092
  KAFKA_SECURITY_PROTOCOL: SASL_SSL
  KAFKA_SASL_MECHANISM: PLAIN
  KAFKA_SASL_USERNAME: kafka_user
  KAFKA_SASL_PASSWORD_ENCRYPTED: 
  KAFKA_SSL_VERIFY: false
  KAFKA_PARTITIONS: 0,1,2
  KAFKA_OFFSET: OFFSET_BEGINNING

  # Schema Registry credentials
  SCHEMA_REGISTRY_URL: schema-registry:8081
  SCHEMA_REGISTRY_USERNAME: registry_user
  SCHEMA_REGISTRY_PASSWORD_ENCRYPTED: 

