SET @sql = CONCAT(
  'CREATE ROUTINE LOAD `example_table_rl` ON `example_table` ',
  'COLUMNS TERMINATED BY '','', ',
  'COLUMNS (uid, column1, column2, column3) ',
  'PROPERTIES ',
  '( ',
    '"desired_concurrent_number"="3", ',
    '"format"="json", ',
    '"max_error_number"="0", ',
    '"max_filter_ratio"="1.0", ',
    '"max_batch_interval"="10", ',
    '"max_batch_rows"="2000000", ',
    '"task_consume_second"="15", ',
    '"task_timeout_second"="60", ',
    '"max_batch_size"="2000000", ',
    '"jsonpaths"="[\\"$.uid\\", \\"$.column1\\", \\"$.column2\\", \\"$.column3\\"]" ' ,
  ') ',
  'FROM KAFKA ',
  '( ',
    '"kafka_broker_list"="', @kafka_broker_list, '", ',
    '"kafka_topic"="example_table", ',
    '"property.security.protocol"="', @kafka_security_protocol, '", ',
    '"property.sasl.mechanism"="', @kafka_sasl_mechanism, '", ',
    '"property.sasl.username"="', @kafka_security_username, '", ',
    '"property.sasl.password"="', @kafka_security_password, '", ',
    '"property.enable.ssl.certificate.verification"="', @kafka_ssl_verify, '", ',
    '"confluent.schema.registry.url"="https://', @schema_registry_username, ':', @schema_registry_password, '\@', @schema_registry_url, '", ',
    '"property.basic.auth.credentials.source"="USER_INFO", ',
    '"kafka_partitions"="0,1,2", ',
    '"property.kafka_default_offsets"="OFFSET_BEGINNING" ' ,
  ');'
);
