include make.env/project.env
include make.env/docker.env
include make.env/dev_image.env
include make.env/database.env
include $(wildcard make.env/${DEV_DB_TYPE}/*.env)
include make.env/cipher.env

export
