version: "3.6"

services:
  dev.db:
    image: ${DEV_DB_IMAGE}
    user: root
    environment: 
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_DATABASE: ${DEV_DB_NAME}
      MSSQL_AGENT_ENABLED: 1
    working_dir: ${DB_HOME}
    ports: 
      - 1434:1433
    volumes:
      - ./mssql/scripts:${DB_HOME}
      # - ./.data/dev_${DEV_DB_NAME}_mssql:/var/opt/mssql